<?xml version="1.0" encoding="utf-8" ?>
<step-package step-type-full-name="ShiftRegisterPackage.ShiftRegister">
    <abbreviation>
        <text>CUS</text>
     </abbreviation>
     <description>This is a ShiftRegister step.</description>
     <mil-modules></mil-modules>
     <assembly name="ShiftRegisterPackage.dll"/>
     <assembly type="UI" name="ShiftRegisterUIPackage.dll"/>
     <assetsRelativeFolder path="assets"/>
</step-package>